apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  labels: 
    app: myappT
    type: front-end
  name: myapp-replicaset
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: myappT
  template: 
    metadata: 
      labels: 
        app: myapp
      name: myapp-pod
    spec: 
      containers: 
        - 
          image: nginx
          name: nginx-container
